feat(kit): use 1 as min segment value in `Date`-related masks
Tinkoff/maskito pull request #197
Opened 2023-03-15 11:29 UTC by vladimirpotekhin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #148

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-03-15 12:49 UTC, nsbarsukov commented on projects/kit/src/lib/utils/date/tests/get-date-segment-value-length.spec.ts
> +        expect(getDateSegmentValueLength('mm.yy')).toEqual({day: 2, month: 2, year: 2});
`{day: 2, month: 2, year: 2}` is expected behaviour ?

not `{day: 0, month: 2, year: 2}` ?

2023-03-15 12:49 UTC, nsbarsukov commented on projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
`2000/0|` => Type `0` => `2000/01|`

https://user-images.githubusercontent.com/35179038/225312813-99e8c063-b84f-4fc4-9245-30c5002128e6.MP4



Should it prevent typing for this case (only for basic typing, for paste/drop etc it okey now) ?

For example, the similar case:
```
`2000/1|` => Type 9 => no changes.
```

2023-03-15 12:49 UTC, nsbarsukov commented on projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
@waterplea @splincode guys, what do you think ?

2023-03-15 12:51 UTC, nsbarsukov commented on projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
I understand that it native dates do this.
```ts
new Date('2023.02.31') // Fri Mar 03 2023 00:00:00 GMT+0300 (GMT+03:00)

```

But i try to figure our is it expected or not 🤔

2023-03-15 13:02 UTC, vladimirpotekhin commented on projects/demo-integrations/cypress/tests/kit/date/date-basic.cy.ts
I thought it was kind of feature) No 🚫 February 30

2023-03-16 14:21 UTC, nsbarsukov approved these changes

2023-03-16 14:21 UTC, nsbarsukov commented on projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts
> +                parseDateString(dateString, dateModeTemplate),
**nitpicking:**

We use `parseDateString` and `parseTimeString` (with the the same args) two times in this file. Inside this `if`-condition and further inside `else`-condition.

Probably, we can move them outside `if/else` (raise it by few lines above).

2023-03-16 14:21 UTC, nsbarsukov commented on projects/kit/src/lib/masks/date-time/postprocessors/min-max-date-time-postprocessor.ts
> +                parseDateString(dateString, dateModeTemplate),
Same case with `createMinMaxDatePostprocessor`

2023-03-16 14:33 UTC, nsbarsukov requested changes
cypress tests fail

2023-03-16 15:11 UTC, vladimirpotekhin commented
> cypress tests fail

removing default values from `getSegmentValueLength` revealed a mistake [here](https://github.com/Tinkoff/maskito/pull/197/files#diff-ad74df28c795dc850018350dc1c76d5c46929e35588b0a3164ce8c4bf9373cdaL42) :peka:

2023-03-16 15:44 UTC, merged